# Pre-commit hooks for live-crew
# Run: uv run pre-commit install
# Update: uv run pre-commit autoupdate

repos:
  # uv dependency management
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.4
    hooks:
      - id: uv-lock
        name: Update uv.lock
        description: Update uv.lock when pyproject.toml changes

  # Ruff linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff
        name: Ruff Linting
        description: Run Ruff linter with --fix
        args: [--fix]
      - id: ruff-format
        name: Ruff Formatting
        description: Run Ruff formatter

  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
      - id: end-of-file-fixer
        name: Fix End of Files
      - id: check-yaml
        name: Check YAML
      - id: check-toml
        name: Check TOML
      - id: check-json
        name: Check JSON
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-case-conflict
        name: Check for case conflicts
      - id: check-docstring-first
        name: Check docstring is first

  # Security checks
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks
        name: GitLeaks
        description: Detect hardcoded secrets

  # Test suite execution
  - repo: local
    hooks:
      - id: pytest
        name: Run Tests
        description: Run pytest test suite with coverage
        entry: uv run pytest --tb=short -v
        language: system
        pass_filenames: false
        always_run: true

# Configuration
default_language_version:
  python: python3.13

# Run hooks on all files during pre-commit install
default_install_hook_types: [pre-commit, pre-push]

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
